default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: taitasu2
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: async_app_development
test:
  <<: *default
  database: async_app_test
production:
  <<: *default
  database: async_app_production
  username: async_app
  password: <%= ENV["ASYNC_APP_DATABASE_PASSWORD"] %>
